#!/usr/bin/env python3
"""Generate protocol/testvectors/vectors.json.

This is a SECOND, INDEPENDENT implementation of the wire format, written from
the tables in protocol/specification.md rather than from core/src/proto/. That
independence is the point: a conformance suite generated by the code it tests
proves only that the code is self-consistent. Two implementations written from
the same spec agreeing is real evidence that the spec is unambiguous and that
both readings of it match.

If this script and core/src/proto/proto.cpp ever disagree, one of them has
misread the specification -- and finding out which is exactly the value here.

Run:  python3 protocol/testvectors/generate.py
"""

import json
import pathlib

VERSION = 1
MAX_DATAGRAM = 1200

TYPE_AUDIO = 0x01
TYPE_PING = 0x02
TYPE_PONG = 0x03
TYPE_JOIN = 0x10
TYPE_METRICS = 0x40

FLAG_TALKSPURT_START = 0x0001
FLAG_TALKSPURT_END = 0x0002
FLAG_FEC = 0x0004
FLAG_DTX = 0x0008
ASSIGNED_FLAG_MASK = 0x000F


def be(value: int, width: int) -> bytes:
    """Big-endian encode, per specification section 1.1."""
    return value.to_bytes(width, "big")


def media(flags: int, stream_id: int, sequence: int, timestamp: int,
          payload: bytes) -> bytes:
    """Specification section 3: 16-byte media header, then the Opus payload.

    Note there is no length field -- the datagram carries its own length.
    """
    return (be(VERSION, 1) + be(TYPE_AUDIO, 1) + be(flags, 2) +
            be(stream_id, 4) + be(sequence, 4) + be(timestamp, 4) + payload)


def control(type_code: int, request_id: int, send_time_us: int,
            body: bytes = b"") -> bytes:
    """Specification section 4: 16-byte control header, then a type-specific body."""
    return (be(VERSION, 1) + be(type_code, 1) + be(0, 2) + be(request_id, 4) +
            be(send_time_us, 8) + body)


def pong_body(orig_t1: int, recv_t2: int) -> bytes:
    """Specification section 4.1: exactly 16 bytes."""
    return be(orig_t1, 8) + be(recv_t2, 8)


vectors = []


def accept_media(name, description, flags, stream_id, sequence, timestamp,
                 payload):
    vectors.append({
        "name": name,
        "description": description,
        "hex": media(flags, stream_id, sequence, timestamp, payload).hex(),
        "expect": "accept",
        "type": "audio",
        "media": {
            "flags": flags,
            "stream_id": stream_id,
            "sequence": sequence,
            "timestamp": timestamp,
            "payload_hex": payload.hex(),
        },
    })


def accept_control(name, description, type_code, type_name, request_id,
                   send_time_us, body=b"", pong=None):
    vector = {
        "name": name,
        "description": description,
        "hex": control(type_code, request_id, send_time_us, body).hex(),
        "expect": "accept",
        "type": type_name,
        "control": {
            "request_id": request_id,
            "send_time_us": send_time_us,
            "body_hex": body.hex(),
        },
    }
    if pong is not None:
        vector["pong"] = pong
    vectors.append(vector)


def reject(name, description, raw: bytes, reason: str):
    vectors.append({
        "name": name,
        "description": description,
        "hex": raw.hex(),
        "expect": "reject",
        "reject": reason,
    })


# ---------------------------------------------------------------- valid media

accept_media(
    "audio-minimal",
    "Smallest legal media packet: the 16-byte header plus a single payload byte.",
    0, 0x11223344, 0x55667788, 0x99AABBCC, bytes([0x7F]))

accept_media(
    "audio-typical",
    "A realistic 20 ms Opus frame at 32 kbps: 80 payload bytes.",
    FLAG_TALKSPURT_START, 0xDEADBEEF, 0x00000001, 0x000003C0,
    bytes((0x40 + (i % 0x30)) for i in range(80)))

accept_media(
    "audio-all-assigned-flags",
    "Every assigned flag bit set at once. All four are independent.",
    ASSIGNED_FLAG_MASK, 0x01020304, 0x05060708, 0x090A0B0C, bytes([0xAA, 0xBB]))

accept_media(
    "audio-flag-fec-only",
    "FEC flag alone. Advisory per section 3.4: a receiver must tolerate it "
    "being set on a payload carrying no usable LBRR.",
    FLAG_FEC, 0x0000FFFF, 0x7FFFFFFF, 0x80000000, bytes([0x01]))

accept_media(
    "audio-flag-dtx-and-end",
    "A DTX frame that also closes the talkspurt.",
    FLAG_DTX | FLAG_TALKSPURT_END, 0xFFFFFFFF, 0x00000000, 0x00000000,
    bytes([0xFE]))

accept_media(
    "audio-sequence-at-wrap",
    "Sequence one below 2^32. A reader using signed 32-bit arithmetic or "
    "assuming small starting values fails here.",
    0, 0xABCDEF01, 0xFFFFFFFF, 0xFFFFFFFE, bytes([0x11, 0x22, 0x33]))

accept_media(
    "audio-all-fields-max",
    "Every 32-bit field at its maximum. Catches a reader that sign-extends.",
    0, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, bytes([0xFF]))

accept_media(
    "audio-max-payload",
    "Largest legal payload: 1200-byte datagram cap minus the 16-byte header.",
    0, 0x12345678, 0x9ABCDEF0, 0x0F1E2D3C,
    bytes((i % 256) for i in range(MAX_DATAGRAM - 16)))

# -------------------------------------------------------------- valid control

accept_control(
    "ping-empty-body",
    "A PING carries no body; its send_time_us is t1 of the section 4.1 exchange.",
    TYPE_PING, "ping", 0x0BADF00D, 0x0000000123456789)

accept_control(
    "ping-max-timestamp",
    "Full 64-bit send_time_us. A reader truncating to 32 bits fails here.",
    TYPE_PING, "ping", 0xFFFFFFFF, 0xFFFFFFFFFFFFFFFF)

accept_control(
    "pong-with-body",
    "A PONG echoes orig_t1 and reports recv_t2; t3 rides in the header's "
    "send_time_us. RTT = (t4-t1) - (t3-t2).",
    TYPE_PONG, "pong", 7, 1_000_480, pong_body(1_000_000, 1_000_450),
    pong={"orig_t1": 1_000_000, "recv_t2": 1_000_450})

accept_control(
    "join-reserved-type",
    "JOIN is assigned but unimplemented in M0. It must parse as a control "
    "packet rather than being rejected as an unknown type.",
    TYPE_JOIN, "join", 1, 42)

accept_control(
    "metrics-highest-assigned-type",
    "0x40 is the highest assigned type code.",
    TYPE_METRICS, "metrics", 0, 0)

# ------------------------------------------------------------------ rejections
# Order is fixed by specification section 6.1: too_short, bad_version,
# unknown_type, reserved_flag, bad_length. Several vectors below are wrong in
# more than one way at once, and pin down which class wins.

for length in range(4):
    reject(f"too-short-{length}-bytes",
           f"{length} bytes: below the 4-byte common prefix of section 2.",
           bytes(range(length)), "too_short")

reject("bad-version-zero",
       "Version 0. Checked before anything else, because no other field's "
       "position can be trusted across versions.",
       be(0, 1) + be(TYPE_AUDIO, 1) + be(0, 2) + bytes(13), "bad_version")

reject("bad-version-two",
       "A v2 sender. A v1 receiver drops all of it rather than part-parsing.",
       be(2, 1) + be(TYPE_AUDIO, 1) + be(0, 2) + bytes(13), "bad_version")

reject("bad-version-wins-over-everything",
       "Bad version AND unassigned type AND a reserved flag AND a short body. "
       "Section 6.1 requires bad_version.",
       be(9, 1) + be(0x7E, 1) + be(0xFFF0, 2), "bad_version")

reject("unknown-type-0x00",
       "Type 0 is unassigned.",
       be(VERSION, 1) + be(0x00, 1) + be(0, 2) + bytes(13), "unknown_type")

reject("unknown-type-0x7e",
       "Type 0x7E is unassigned.",
       be(VERSION, 1) + be(0x7E, 1) + be(0, 2) + bytes(13), "unknown_type")

reject("unknown-type-0xff",
       "Type 0xFF is unassigned.",
       be(VERSION, 1) + be(0xFF, 1) + be(0, 2) + bytes(13), "unknown_type")

reject("unknown-type-wins-over-flags",
       "Unassigned type AND a reserved flag. Type is checked first.",
       be(VERSION, 1) + be(0x7E, 1) + be(0x0010, 2) + bytes(13), "unknown_type")

for bit in (4, 8, 15):
    mask = 1 << bit
    reject(f"reserved-media-flag-bit-{bit}",
           f"Media flag bit {bit} is reserved. Section 7 requires failing "
           "closed: ignoring it could mean decoding ciphertext or duplicating "
           "audio, which surfaces as an artefact instead of a counter.",
           media(mask, 1, 1, 1, bytes([0x01])), "reserved_flag")

reject("reserved-media-flag-with-valid-flags",
       "An assigned flag plus a reserved one. Still rejected.",
       media(FLAG_FEC | 0x0100, 1, 1, 1, bytes([0x01])), "reserved_flag")

reject("reserved-control-flag",
       "Control flags are entirely reserved in v1.",
       be(VERSION, 1) + be(TYPE_PING, 1) + be(0x0001, 2) + be(1, 4) + be(1, 8),
       "reserved_flag")

reject("reserved-flag-wins-over-length",
       "A reserved flag AND a header-only length. Flags are checked first.",
       media(0x0010, 1, 1, 1, b""), "reserved_flag")

reject("audio-header-only",
       "Exactly 16 bytes: no payload means no audio, so this is malformed "
       "rather than an empty frame.",
       media(0, 1, 1, 1, b""), "bad_length")

reject("audio-truncated-header",
       "15 bytes: a valid prefix but an incomplete media header.",
       media(0, 1, 1, 1, b"")[:15], "bad_length")

reject("audio-over-cap",
       "1201 bytes: one past the 1200-byte datagram cap of section 1.1.",
       media(0, 1, 1, 1, bytes(MAX_DATAGRAM - 16 + 1)), "bad_length")

reject("control-truncated",
       "10 bytes: a valid prefix but an incomplete control header.",
       control(TYPE_PING, 1, 1)[:10], "bad_length")

reject("control-over-cap",
       "One past the datagram cap, with a valid control header.",
       control(TYPE_PING, 1, 1, bytes(MAX_DATAGRAM - 16 + 1)), "bad_length")

# ------------------------------------------------------------------------ emit

output = {
    "protocol_version": VERSION,
    "note": (
        "Normative conformance vectors for protocol/specification.md. Generated "
        "by generate.py, which is an independent implementation of the wire "
        "format written from the specification rather than from the C++ "
        "encoder. Every port -- C++, Android/JNI, iOS/Swift -- must pass all of "
        "these. Cross-platform interop is established by both ends passing "
        "these vectors, not by two devices appearing to work side by side."
    ),
    "vectors": vectors,
}

path = pathlib.Path(__file__).parent / "vectors.json"
path.write_text(json.dumps(output, indent=2) + "\n")

accepts = sum(1 for v in vectors if v["expect"] == "accept")
print(f"wrote {path} -- {len(vectors)} vectors ({accepts} accept, "
      f"{len(vectors) - accepts} reject)")
