// Conformance against protocol/testvectors/vectors.json.
//
// The vectors are produced by protocol/testvectors/generate.py, which is an
// independent implementation of the wire format written from
// protocol/specification.md rather than from core/src/proto/. That independence
// is what gives this file its value: a conformance suite generated by the code
// it tests proves only self-consistency. Two implementations written separately
// from the same spec agreeing is evidence that the spec is unambiguous and that
// both readings match.
//
// The same vectors will be run from a JNI test on Android and a Swift test on
// iOS. Cross-platform interop is established by every port passing this file,
// not by two devices appearing to work when placed side by side.
#include <catch2/catch_test_macros.hpp>
#include <nlohmann/json.hpp>

#include <cstddef>
#include <cstdint>
#include <fstream>
#include <set>
#include <string>
#include <vector>

#include "radio/proto.hpp"

using namespace radio;

namespace {

std::vector<std::byte> from_hex(const std::string& hex) {
  REQUIRE(hex.size() % 2 == 0);
  std::vector<std::byte> out;
  out.reserve(hex.size() / 2);
  const auto nibble = [](char c) -> int {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
  };
  for (std::size_t i = 0; i < hex.size(); i += 2) {
    const int high = nibble(hex[i]);
    const int low = nibble(hex[i + 1]);
    REQUIRE(high >= 0);
    REQUIRE(low >= 0);
    out.push_back(static_cast<std::byte>((high << 4) | low));
  }
  return out;
}

std::string to_hex(ByteView bytes) {
  static const char* digits = "0123456789abcdef";
  std::string out;
  out.reserve(bytes.size() * 2);
  for (const auto byte : bytes) {
    const auto value = std::to_integer<std::uint8_t>(byte);
    out.push_back(digits[value >> 4]);
    out.push_back(digits[value & 0x0F]);
  }
  return out;
}

proto::Reject reject_from_name(const std::string& name) {
  if (name == "too_short") return proto::Reject::TooShort;
  if (name == "bad_version") return proto::Reject::BadVersion;
  if (name == "unknown_type") return proto::Reject::UnknownType;
  if (name == "reserved_flag") return proto::Reject::ReservedFlag;
  if (name == "bad_length") return proto::Reject::BadLength;
  FAIL("unknown reject class in vectors.json: " << name);
  return proto::Reject::None;
}

nlohmann::json load_vectors() {
  const std::string path = std::string(RADIO_TESTVECTORS_DIR) + "/vectors.json";
  std::ifstream file(path);
  REQUIRE_FALSE(file.fail());
  nlohmann::json document;
  file >> document;
  return document;
}

// A reject vector does not say which parser to use, so pick by the type byte
// when the prefix is intact enough to read one. Both parsers validate the full
// prefix themselves, so either is correct for a prefix-level rejection.
proto::Reject reject_via_typed_parser(ByteView datagram) {
  if (datagram.size() >= 2 &&
      std::to_integer<std::uint8_t>(datagram[0]) == proto::kVersion) {
    const auto type =
        static_cast<proto::Type>(std::to_integer<std::uint8_t>(datagram[1]));
    if (proto::is_assigned(type) && !proto::is_media(type)) {
      return proto::parse_control(datagram).reject;
    }
  }
  return proto::parse_media(datagram).reject;
}

}  // namespace

TEST_CASE("the vector file itself is intact") {
  // Guards against a truncated or half-regenerated file silently reducing
  // coverage to nothing.
  const auto document = load_vectors();
  CHECK(document.at("protocol_version").get<int>() == proto::kVersion);

  const auto& vectors = document.at("vectors");
  CHECK(vectors.size() >= 30);

  std::set<std::string> reject_classes;
  std::set<std::string> accepted_types;
  for (const auto& vector : vectors) {
    if (vector.at("expect") == "reject") {
      reject_classes.insert(vector.at("reject").get<std::string>());
    } else {
      accepted_types.insert(vector.at("type").get<std::string>());
    }
  }

  // Every rejection class in the spec must be exercised.
  CHECK(reject_classes == std::set<std::string>{"bad_length", "bad_version",
                                                "reserved_flag", "too_short",
                                                "unknown_type"});
  CHECK(accepted_types.count("audio") == 1);
  CHECK(accepted_types.count("ping") == 1);
  CHECK(accepted_types.count("pong") == 1);
}

TEST_CASE("every accept vector decodes to the specified fields") {
  const auto document = load_vectors();

  for (const auto& vector : document.at("vectors")) {
    if (vector.at("expect") != "accept") continue;

    const auto name = vector.at("name").get<std::string>();
    const auto description = vector.at("description").get<std::string>();
    INFO("vector '" << name << "': " << description);

    const auto bytes = from_hex(vector.at("hex").get<std::string>());
    const ByteView datagram{bytes.data(), bytes.size()};

    const auto type = proto::peek_type(datagram);
    REQUIRE(type.ok());

    if (vector.at("type") == "audio") {
      REQUIRE(type.value == proto::Type::Audio);
      const auto parsed = proto::parse_media(datagram);
      REQUIRE(parsed.ok());

      const auto& expected = vector.at("media");
      CHECK(parsed.value.header.flags ==
            expected.at("flags").get<std::uint16_t>());
      CHECK(parsed.value.header.stream_id ==
            expected.at("stream_id").get<std::uint32_t>());
      CHECK(parsed.value.header.sequence ==
            expected.at("sequence").get<std::uint32_t>());
      CHECK(parsed.value.header.timestamp ==
            expected.at("timestamp").get<std::uint32_t>());
      CHECK(to_hex(parsed.value.payload) ==
            expected.at("payload_hex").get<std::string>());
    } else {
      REQUIRE(type.value != proto::Type::Audio);
      const auto parsed = proto::parse_control(datagram);
      REQUIRE(parsed.ok());

      const auto& expected = vector.at("control");
      CHECK(parsed.value.header.request_id ==
            expected.at("request_id").get<std::uint32_t>());
      CHECK(parsed.value.header.send_time_us ==
            expected.at("send_time_us").get<std::uint64_t>());
      CHECK(to_hex(parsed.value.body) ==
            expected.at("body_hex").get<std::string>());

      if (vector.contains("pong")) {
        const auto body = proto::parse_pong_body(parsed.value.body);
        REQUIRE(body.ok());
        CHECK(body.value.orig_t1 ==
              vector.at("pong").at("orig_t1").get<std::uint64_t>());
        CHECK(body.value.recv_t2 ==
              vector.at("pong").at("recv_t2").get<std::uint64_t>());
      }
    }
  }
}

TEST_CASE("every reject vector is rejected with the specified class") {
  // The class matters, not just the rejection. Spec section 6.1 fixes the
  // evaluation order precisely so that telemetry is comparable between ports --
  // "bad_version: 40" has to mean the same thing on Android as it does here.
  const auto document = load_vectors();

  for (const auto& vector : document.at("vectors")) {
    if (vector.at("expect") != "reject") continue;

    const auto name = vector.at("name").get<std::string>();
    const auto description = vector.at("description").get<std::string>();
    INFO("vector '" << name << "': " << description);

    const auto bytes = from_hex(vector.at("hex").get<std::string>());
    const ByteView datagram{bytes.data(), bytes.size()};
    const auto expected =
        reject_from_name(vector.at("reject").get<std::string>());

    // No parser may accept it, whichever one is asked.
    CHECK_FALSE(proto::parse_media(datagram).ok());
    CHECK_FALSE(proto::parse_control(datagram).ok());

    CHECK(reject_via_typed_parser(datagram) == expected);

    // The three prefix-level classes must also be visible to peek_type, which
    // is what the receive loop calls before touching any stream state.
    if (expected == proto::Reject::TooShort ||
        expected == proto::Reject::BadVersion ||
        expected == proto::Reject::UnknownType) {
      CHECK(proto::peek_type(datagram).reject == expected);
    }
  }
}

TEST_CASE("re-encoding an accept vector reproduces its bytes exactly") {
  // Round-trip through our own encoder. A decoder can be right while an encoder
  // is wrong -- for instance by writing a field at the correct offset in the
  // wrong byte order, which a symmetric round-trip inside one implementation
  // would never catch. Comparing against externally generated bytes does.
  const auto document = load_vectors();
  std::vector<std::byte> out(proto::kMaxDatagram);

  for (const auto& vector : document.at("vectors")) {
    if (vector.at("expect") != "accept") continue;

    const auto name = vector.at("name").get<std::string>();
    INFO("vector '" << name << "'");

    const auto expected_hex = vector.at("hex").get<std::string>();
    const auto bytes = from_hex(expected_hex);
    const ByteView datagram{bytes.data(), bytes.size()};

    std::size_t written = 0;

    if (vector.at("type") == "audio") {
      const auto parsed = proto::parse_media(datagram);
      REQUIRE(parsed.ok());
      written =
          proto::encode_media(parsed.value.header, parsed.value.payload, out);
    } else {
      const auto parsed = proto::parse_control(datagram);
      REQUIRE(parsed.ok());
      proto::ControlHeader header = parsed.value.header;
      header.type = parsed.value.header.type;
      written = proto::encode_control(header, parsed.value.body, out);
    }

    REQUIRE(written == bytes.size());
    CHECK(to_hex(ByteView{out.data(), written}) == expected_hex);
  }
}
